name: amd64_windows_gcc

on: [push, pull_request]

jobs:

  amd64_windows_gcc:
    runs-on: windows-2019
    timeout-minutes: 5
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve test compression corpus
      run: |
        git clone https://github.com/ariya/compression-corpus.git
        cd compression-corpus
        cd enwik
        unzip enwik8.zip
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make
    - run: gcc --version
    - run: cd tests && make roundtrip
      name: Perform round-trip tests
    - name: 'Build examples: 6pack and 6unpack'
      run: cd examples && make
    - name: 'Run examples: 6pack and 6unpack'
      run: |
        cd examples
        ./6pack -v
        ./6pack ../compression-corpus/enwik/enwik8.txt archive.6pk
        ./6unpack -v
        ./6unpack archive.6pk
